### ISSUE TITLE
Register scan returns inconsistent results

### ISSUE THREAD

**Issue by sbadger** [SciFiDryer/ModbusMechanic#19]
While using the register scanner I noticed that values I expected would jump around between the registers on almost every scan.

**To Reproduce**
Open up the register scanner and scan a node using tcp and note a value. 
Scan again and then note that the value you are looking for moved to a new registery

Running on Fedora 38

$ java -version
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment (Red_Hat-17.0.7.0.7-4.fc38) (build 17.0.7+7)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.7.0.7-4.fc38) (build 17.0.7+7, mixed mode, sharing)

**Comment by SciFiDryer** [comment]
This is a new and experimental feature so your testing and feedback are helpful. That said, is this a RTU device attached to a TCP bridge? I noticed when scanning RTU devices that the scan can get "ahead" of the device's responses. What I see in the scan results when this happens is the register values are shifted anywhere from 20 to 30 lower from what the scan reads. For instance register 1020 is actually 1000. I haven't been able to replicate this (yet) on TCP though. Do you know if the register order might still be correct?

**Comment by sbadger** [comment]
It was a tcp scan
I believe the order was correct. I will have to redo the scan and send you
the screenshots and check that the order are proper

**Comment by sbadger** [comment]
I redid the scan this morning and the values jumped all over the place. For
instance in the first screenshot the registry for the battery voltage is
894 and then it moves to 902 and then to 882 in the last scan. The real
registry value for that item is 840.

**Comment by SciFiDryer** [comment]
I think I see what is happening. The TCP scanner is also getting ahead of the device's ability to respond. Transaction numbers are not tagged, which is confusing the scanner. This should be fixed in bfcf0c0 which tags transaction IDs on TCP frames.

The screenshots did not come through, but if you start the scan at register 840 instead of 0 do you get consistent results for that first register or first few registers?

**Comment by sbadger** [comment]
Your suspensions are correct. If I start the scan at 840 the value is where
I expect it and the further away I get from the 840 the values start drift
all over the place

I now have values in registers 2959 and 2960 that were in the 3000 range on
the previous scans.

**Comment by SciFiDryer** [comment]
I realized the other thing that might be going on is a _buffer_ issue. Since this library blocks on a read, if the device doesn't respond fast enough there could be a FIFO situation happening on the buffer where the previous responses are accumulating but never read out. In 73416f1 I have added a user configurable timeout and set the default to 100ms, up from the current hard coded value of 50ms. The timeout should be higher than the devices ping. These changes will be available in the next release and between the two should resolve the issue.

**Comment by sbadger** [comment]
This particular device is in the other side of a star link connection so
the latency is all over the place and the device is also slow. I guess that
is the perfect storm for exposing this flaw!

**Comment by SciFiDryer** [comment]
Binaries for version 2.8 have just been posted. If the registers are still out of order after playing around with the timeout let me know.

**Comment by SciFiDryer** [comment]
This will be closed in the next day or so unless the problem still can be recreated in tests.
